### ISSUE TITLE
Question regarding file to train

### ISSUE THREAD

**Issue by CZLam7** [William-wAng618/M2PT#1]
![image](https://github.com/user-attachments/assets/70a0dd73-1203-42f4-ba7c-aec8208e63c5)
Hi, the following is the screenshot from scripts/PT_full_schedule.sh, which is executed during training. However there's no such directory for llavaPT after I git clone the directory. There're only llava and M2PT. Are we supposed to run the training file from M2PT instead? 

Many Thanks

**Comment by William-wAng618** [comment]
Yes exactly, I modified the running script. run from M2PT pls
